name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      BACKEND_IMAGE: konuamah/backend
      FRONTEND_IMAGE: konuamah/frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend image
      working-directory: ./backend
      run: |
        docker build -t $BACKEND_IMAGE:latest .
        docker push $BACKEND_IMAGE:latest

    - name: Build and push Frontend image
      working-directory: ./frontend
      run: |
        docker build -t $FRONTEND_IMAGE:latest .
        docker push $FRONTEND_IMAGE:latest 
